### ISSUE TITLE
Possible mistake, JSON of StatusCode ?

### ISSUE THREAD

**Issue by crbrox** [LeandroGuillen/gongsi#1]
Should be 

```
type StatusCode struct {
    Code         int    `json:"code"`
```

instead of 

```
type StatusCode struct {
    Code         int    `json:"name"`
```

?
https://github.com/LeandroGuillen/gongsi/blob/develop/dataStructures.go#L89

**Comment by LeandroGuillen** [comment]
Absolutely! Thanks for the catch.

Fixed in 75d8f7b276c36c831b7a3605728593f65237d66e
